[package]
name = "bounce-sim"
version = "0.1.0"
authors = ["Taegyun Kim <k.taegyun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
num-bigint = "0.2.6"
pkcs11 = "0.5.0"
openssl-sys = "0.9"
openssl = "0.10"
