[package]
name = "bounce"
version = "0.1.0"
authors = ["Taegyun Kim <k.taegyun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rand = { version = "0.6" }
secp256k1 = { version = "0.20.1", features = ["rand", "bitcoin_hashes"] }

[dev-dependencies]
num-bigint = "0.2.6"
openssl-sys = "0.9"
openssl = "0.10"
pkcs11 = "0.5.0"

[[bin]]
name = "cubesat"
path = "bin/cubesat.rs"
